/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.telu.dekstop.view.admin;

import com.telu.dekstop.view.*;
import java.awt.CardLayout;

/**
 *
 * @author maula
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminFrame
     */
    
    public AdminFrame(String role) {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        
        if("Cashier".equalsIgnoreCase(role)){
            menuMasterData.setVisible(false);
            
            // langsung redirect ke menu kasir
            CardLayout layout = (CardLayout) jPanel1.getLayout();
            layout.show(jPanel1, "cashier");
            cashierPanel1.reload();
        }else {
            userPanel.reload();
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userPanel = new com.telu.dekstop.view.admin.panel.UserPanel();
        itemPanel = new com.telu.dekstop.view.admin.panel.ItemPanel();
        kategoriPanel = new com.telu.dekstop.view.admin.panel.KategoriPanel();
        cashierPanel1 = new com.telu.dekstop.view.admin.panel.CashierPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuLogOut = new javax.swing.JMenuItem();
        menuMasterData = new javax.swing.JMenu();
        menuItem = new javax.swing.JMenuItem();
        menuKategori = new javax.swing.JMenuItem();
        menuUser = new javax.swing.JMenuItem();
        menuKasir = new javax.swing.JMenu();
        menuCashier = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.CardLayout());
        jPanel1.add(userPanel, "user");
        jPanel1.add(itemPanel, "item");
        jPanel1.add(kategoriPanel, "kategori");
        jPanel1.add(cashierPanel1, "cashier");

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        menuLogOut.setText("Log Out");
        menuLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogOutActionPerformed(evt);
            }
        });
        jMenu1.add(menuLogOut);

        jMenuBar1.add(jMenu1);

        menuMasterData.setText("Master Data");

        menuItem.setText("Item");
        menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemActionPerformed(evt);
            }
        });
        menuMasterData.add(menuItem);

        menuKategori.setText("Kategori");
        menuKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKategoriActionPerformed(evt);
            }
        });
        menuMasterData.add(menuKategori);

        menuUser.setText("Data User");
        menuUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUserActionPerformed(evt);
            }
        });
        menuMasterData.add(menuUser);

        jMenuBar1.add(menuMasterData);

        menuKasir.setText("Pesanan & Kasir");

        menuCashier.setText("Menu Kasir");
        menuCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCashierActionPerformed(evt);
            }
        });
        menuKasir.add(menuCashier);

        jMenuBar1.add(menuKasir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) jPanel1.getLayout();
        layout.show(jPanel1, "item");
        itemPanel.reload();
    }//GEN-LAST:event_menuItemActionPerformed

    private void menuKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKategoriActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) jPanel1.getLayout();
        layout.show(jPanel1, "kategori");
        kategoriPanel.reload();
    }//GEN-LAST:event_menuKategoriActionPerformed

    private void menuUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUserActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) jPanel1.getLayout();
        layout.show(jPanel1, "user");
        userPanel.reload();
    }//GEN-LAST:event_menuUserActionPerformed

    private void menuCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCashierActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) jPanel1.getLayout();
        layout.show(jPanel1, "cashier");
        cashierPanel1.reload();
    }//GEN-LAST:event_menuCashierActionPerformed

    private void menuLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogOutActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_menuLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.telu.dekstop.view.admin.panel.CashierPanel cashierPanel1;
    private com.telu.dekstop.view.admin.panel.ItemPanel itemPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private com.telu.dekstop.view.admin.panel.KategoriPanel kategoriPanel;
    private javax.swing.JMenuItem menuCashier;
    private javax.swing.JMenuItem menuItem;
    private javax.swing.JMenu menuKasir;
    private javax.swing.JMenuItem menuKategori;
    private javax.swing.JMenuItem menuLogOut;
    private javax.swing.JMenu menuMasterData;
    private javax.swing.JMenuItem menuUser;
    private com.telu.dekstop.view.admin.panel.UserPanel userPanel;
    // End of variables declaration//GEN-END:variables


}
