/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.telu.dekstop.view.admin.panel;

import com.stripbandunk.jwidget.model.DefaultPaginationModel;
import com.stripbandunk.jwidget.model.DynamicTableModel;
import com.telu.dekstop.controller.UserController;
import com.telu.dekstop.model.User;
import com.telu.dekstop.view.admin.dialog.UserDialog;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author maula
 */
public class UserPanel extends javax.swing.JPanel {
    
    private DynamicTableModel<User> tableModel;
    private final int PAGE_SIZE = 10;
    /**
     * Creates new form KelolaMenuPanel
     */
    public UserPanel() {
        initComponents();
        tableModel = new DynamicTableModel<>(User.class);
        jDynamicTable1.setDynamicModel(tableModel);
        jDynamicTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
    }
    
    public void reload() {
        UserController controller = new UserController();
        
        int totalItem = controller.count().intValue();
        DefaultPaginationModel paginationModel = new DefaultPaginationModel(PAGE_SIZE, totalItem);
        jPagination1.setModel(paginationModel);
        
        List<User> select = controller.getAll(0, PAGE_SIZE);
        tableModel.clear();
        for (User user : select) {
            tableModel.add(user);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDynamicTable1 = new com.stripbandunk.jwidget.JDynamicTable();
        jPagination1 = new com.stripbandunk.jwidget.JPagination();
        jPanel1 = new javax.swing.JPanel();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReload = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Data User");

        jScrollPane1.setViewportView(jDynamicTable1);

        jPagination1.addPaginationListener(new com.stripbandunk.jwidget.listener.PaginationListener() {
            public void onPageChange(com.stripbandunk.jwidget.event.PaginationEvent evt) {
                jPagination1OnPageChange(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridBagLayout());

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsert, new java.awt.GridBagConstraints());

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new java.awt.GridBagConstraints());

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new java.awt.GridBagConstraints());

        btnReload.setText("Reload");
        btnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadActionPerformed(evt);
            }
        });
        jPanel1.add(btnReload, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(539, 539, 539))
            .addComponent(jPagination1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPagination1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        UserDialog dialog = new UserDialog();
        User hasilUser = dialog.tambah();
        
        if(hasilUser != null){
            UserController controller = new UserController();
            boolean success = controller.insert(hasilUser);
            
            if(success){
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
                reload();
            }else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        if(jDynamicTable1.getSelectedRow() != -1){
            User parameter = tableModel.get(jDynamicTable1.convertRowIndexToModel(jDynamicTable1.getSelectedRow()));
       
            UserDialog dialog = new UserDialog();
            User hasilUser = dialog.ubah(parameter);

            if(hasilUser != null){
                UserController controller = new UserController();
                boolean success = controller.update(hasilUser);
                
                if(success){
                    JOptionPane.showMessageDialog(this, "Data berhasil diubah");
                    reload();
                }else {
                    JOptionPane.showMessageDialog(this, "Data gagal diubah", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }    
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu!");
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        if(jDynamicTable1.getSelectedRow() != -1){
            if(JOptionPane.showConfirmDialog(this, "Apakah anda takin ingin menghapus data?", "Hapus Data", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
                User parameter = tableModel.get(jDynamicTable1.convertRowIndexToModel(jDynamicTable1.getSelectedRow()));
                
                UserController controller = new UserController();
                boolean success = controller.delete(parameter);
                
                if(success){
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                    reload();
                }else {
                    JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }  
        }else {
            JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu");
        }
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadActionPerformed
        // TODO add your handling code here:
        reload();
    }//GEN-LAST:event_btnReloadActionPerformed

    private void jPagination1OnPageChange(com.stripbandunk.jwidget.event.PaginationEvent evt) {//GEN-FIRST:event_jPagination1OnPageChange
        // TODO add your handling code here:
        int skip = (evt.getCurrentPage() - 1) * evt.getPageSize();
        int max = evt.getPageSize();

        UserController controller = new UserController();
        List<User> items = controller.getAll(skip, max);
        tableModel.clear();
        for (User item : items) {
            tableModel.add(item);
        }
    }//GEN-LAST:event_jPagination1OnPageChange
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnReload;
    private javax.swing.JButton btnUpdate;
    private com.stripbandunk.jwidget.JDynamicTable jDynamicTable1;
    private javax.swing.JLabel jLabel1;
    private com.stripbandunk.jwidget.JPagination jPagination1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
