/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.telu.dekstop.view.customer.dialog;

import com.telu.dekstop.model.Cart;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author maula
 */
public class CheckoutDialog extends javax.swing.JDialog {

    /**
     * Creates new form CheckoutDialog
     */
    public CheckoutDialog() {
        setModal(true);
        initComponents();
        
        paymentMethod();
    }
    
    private boolean confirmed = false;
    private String selectedPaymentMethod;
    
    public boolean isConfirmed(){
        return confirmed;
    }
    
    public void setCartItem(List<Cart> cartitems) {
        
        StringBuilder ringkasanPesanan = new StringBuilder();
        int total = 0;
        
        for (Cart cart : cartitems) {
            ringkasanPesanan.append(cart.toString()).append("\n");
            total += cart.getItem_id().getPrice() * cart.getQuantity();
        }
        ringkasanPesanan.append("Total yang harus dibayar: Rp." + total);
        
        orderSummary.setText(ringkasanPesanan.toString());
        orderSummary.setEditable(false);
    }
    
    public void paymentMethod(){
        ButtonGroup paymentMethodGroup = new ButtonGroup();
        paymentMethodGroup.add(jRadioButton1);
        paymentMethodGroup.add(jRadioButton2);
       
    }
   
    public void paymentMethodSelected(){
        if(jRadioButton1.isSelected()){
            confirmed = true;
            selectedPaymentMethod = "QRIS";
            
            QrisDialog dialog = new QrisDialog(this);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        }else if (jRadioButton2.isSelected()){
            confirmed = true;
            selectedPaymentMethod = "Bayar di Kasir";
            
            JOptionPane.showMessageDialog(this, "Silahkan bayar dikasir");
            dispose();
        }else {
            JOptionPane.showMessageDialog(this, "Pilih salah satu metode pembayaran!");
        }
    }
    
    public String getSelectedPaymentMethod(){
        return selectedPaymentMethod;
    }
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderSummary = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        btnConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Ringkasan Pesanan :");
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        orderSummary.setColumns(20);
        orderSummary.setRows(5);
        orderSummary.setFocusable(false);
        orderSummary.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(orderSummary);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pilih Metode Pembayaran:");

        jRadioButton1.setText(" Bayar via QRIS");
        jRadioButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jRadioButton2.setText("Bayar di Kasir");
        jRadioButton2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnConfirm.setText("Konfirmasi");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
            .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(btnConfirm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        paymentMethodSelected(); 
    }//GEN-LAST:event_btnConfirmActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea orderSummary;
    // End of variables declaration//GEN-END:variables
}
